added attack functionallity
Ran-Regev-HLS/Pokedex-Backend pull request #3
Opened 2024-12-01 14:27 UTC by Ran-Regev-HLS

### Changes Made
> added attack endpoint

I have:
- [ ] deleted all irrelevant comments.
- [ ] deleted all irrelevant logs and debuggers.
- [ ] deleted all sensitive information.
- [ ] made sure my code is generic and reusable for future things or reused existing resources.
- [ ] made sure that my code is readable.
- [ ] checked that the functions and resource names are self-explanatory.
- [ ] tested the code locally and it works as expected.
- [ ] added validations and error handling in relevant cases (external requests, integrations, etc).

2024-12-01 19:40 UTC, kfir-azu requested changes

2024-12-01 19:40 UTC, kfir-azu commented on src/fighting/fighting.service.ts
> +      {},
set default values for the getFilteredPokemons so you won't have to send the whole props every time.

2024-12-01 19:40 UTC, kfir-azu commented on src/fighting/fighting.service.ts
> +    if (!fighting) {
Move this to controller

2024-12-01 19:40 UTC, kfir-azu commented on src/fighting/fighting.service.ts
> +    const attackerId =
Export to a util function getAttackerId

2024-12-01 19:40 UTC, kfir-azu commented on src/fighting/fighting.service.ts
> +    const defenderHpKey: keyof Fighting =
export to a util function

2024-12-01 19:40 UTC, kfir-azu commented on src/fighting/fighting.service.ts
> +  async processAttack(
We need to simplify this function -  i have added comments to add util functions, please split each flow to a util function - I think you need to add comments that specifies the flow of the function as well as there are many things going on here

2024-12-01 19:40 UTC, kfir-azu commented on src/fighting/utils.ts
> +export function calculateAttack(
Add the type advantage to the calculation

2024-12-02 19:54 UTC, kfir-azu requested changes

2024-12-02 19:54 UTC, kfir-azu commented on src/fighting/dtos/fighting.dto.ts
Change file name

2024-12-02 19:54 UTC, kfir-azu commented on src/fighting/fighting.controller.ts
> +    @Query() attack: AttackDto,
You get the attack from the query or from the body?

2024-12-02 19:54 UTC, kfir-azu commented on src/fighting/fighting.repository.ts
> +    id: string,
if you get it as a string you need to transform it to new Types.ObjectId(id) to find it.
use mongo _id and not pokemon id. 
using object ids is much easier for mongo

2024-12-03 07:40 UTC, Ran-Regev-HLS commented on src/fighting/dtos/fighting.dto.ts
this will hold catch and switch dtos as well (i can do one file each but they are all quite small)

2024-12-04 06:48 UTC, kfir-azu approved these changes

2024-12-04 06:48 UTC, kfir-azu commented on src/fighting/fighting.repository.ts
> +import { Model, ObjectId, Types } from 'mongoose';
Remove unused imports

2024-12-04 08:01 UTC, merged